### ISSUE TITLE
[enh] Son of Dracula theme/style

### ISSUE THREAD

**Issue by STrRedWolf** [ctklainow/stealth-ux#1]
So far so good.  In my case, I don't need the OH MY BASH scripts, but thankfully that's easily reverted.

However... Dracula's put on weight, and no-border is missing a border. :)  

Can you add a "Son of Dracula" that takes the same size as greybird-compact but has the white title active/grey title inactive?

**Comment by zekekin** [comment]
I can definitely try! Should have more time later this week to give it a shot :+1:

**Comment by zekekin** [comment]
@STrRedWolf I made some changes to Dracula and pushed a new "dracula-compact". Give it a shot:

        sudo cp -r dracula-compact/ ${HOME}/.local/share/themes

![Preview](https://i.imgur.com/fIBHoMU.png)

**Comment by STrRedWolf** [comment]
So far so good!  Here's what it looks like on my PARROT:

![CBAkairo-Dracula-Compact](https://user-images.githubusercontent.com/979792/94344317-6af49500-ffec-11ea-837e-c6906307d86a.png)

Only minor tolerable nit to pick is the shade/min/max/close buttons being MacOS like instead of Windows like (although I wish for NeXT-like). Eh, I may fork the code and tweak it myself then, so don't worry about it.

I should look into the GTK theme, see if I can compact/slim it down...

**Comment by zekekin** [comment]
Looks good! I documented the [instructions for slimming down the Dracula GTK theme](https://github.com/ctklainow/stealth-ux/blob/master/dracula-compact/xfwm4/changes.md), it can help you if you want to start tweaking GTK themes. Let me know if you run into problems. If you want it even slimmer, just delete a few lines of code in the corresponding XPM files (you'll know what I mean when you read the doc)
